config/routes.rb
Rails.application.routes.draw do
  get "welcome/index"
  root "welcome#index"
  resources :restaurants do
    resources :ratings
  end
  resources :reviews
  resources :categories

  post "/users" => "users#create"
  # get "/users" => "users#index"
  # get "/users/:id" => "users#show"
  resources :users, only: [:index, :show]
  get "/signup" => "users#new"
  get "/signin" => "sessions#new"
  post "/signin" => "sessions#create"
  get "/signout" => "sessions#destroy"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :restaurants
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :restaurant
  # why'd you take these out?
  # validates_presence_of :restaurant
  # validates_inclusion_of :value, in => 1..10
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_many :reviews, :dependent => :destroy
  has_many :ratings, :dependent => :destroy
  belongs_to :category

  def average_rating
    return 5.5 if self.ratings.empty?

    total = 0
    self.ratings.each do |rat|
      total = total + rat.value
    end

    avg = total / self.ratings.count
  end



end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    if session[:user_id]
      return User.find(session[:user_id])
    else
      return nil
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: "Category Successfully Created"
    else
      render :new
    end
  end


  def edit
    @category = Category.find(params[:id])
  end

  def update
    cleaned_params = params.require(:category).permit(:category)
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private
    def category_params
      params.require(:category).permit(:category)
    end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_filter :set_restaurant

  def create
    # The line below isn't wrong, but it's not really written using modern ruby
    # style... here's how I'd write it:
    # @rating = @restaurant.ratings.new(value: params[:rating][:value])

    @rating = @restaurant.ratings.new :value => params[:rating][:value]
    if @rating.save
      redirect_to restaurant_path(@restaurant), :notice => "Rating successful."
    else
      redirect_to restaurant_path(@restaurant), :notice => "Something went wrong."
    end
  end

  # there's no interface to update a rating as far as I can tell... I don't think
  # this should be necessary.
  def update
    @rating = Rating.find(params[:id])
    @rating.update_attribute :value, params[:value]
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @rating = Rating.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
      @restaurant = Restaurant.new(restaurant_params)
      if @restaurant.save
        redirect_to @restaurant, notice: "Restaurant Successfully Created"
      else
        render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path, notice: "Restaurant Successfully Deleted"
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :photo_url, :category_id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    cleaned_params = params.require(:review).permit(:comment, :restaurant_id)
    @review = Review.create(cleaned_params)
    # it'd be really nice if you took advantage of your user auth here to
    # do something like below so that reviews belonged to a user:
    # @review.user = current_user
    # You'd have to update your DB to include a user_id column on reviews of course
    redirect_to @review.restaurant
  end

  def edit
    @review = Review.find(params[:id])
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    # just like the comment_params below, this seems to be incorrect and pulled
    # from another example, as it references a 'post_id'
    cleaned_params = params.require(:review).permit(:comment, :post_id)
    @review = Review.find(params[:id])
    if @review.update(cleaned_params)
      redirect_to @review.restaurant
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to @review.restaurant
  end

  private
    # you defined this method but then never use it! Also, it seems to be copied
    # from some other app / context that doesn't quite apply here. Be careful
    # blindly copying code without thinking about how it works and what it's doing!
    def comment_params
      params.require(:comment).permit(:post_id, :comment)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])

    if user
      if user.authenticate(params[:password])
        session[:user_id] = user.id
        flash[:notice] = "Logged in as #{user.username}"
        redirect_to restaurants_path
      else
        render :new and return
      end
    else
      render :new and return
    end
  end


def destroy
  session[:user_id] = nil
  redirect_to welcome_index_path, notice: "Signed Out!"
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to restaurants_path, notice: "Signed Up Successfully"
    else
      render :new
    end
  end

  def show
    @user = current_user
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <ul>
        <h2>errors:</h2>
        <% @category.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <% end %>
      </ul>
    </div>
  <% end  %>
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
 <% end %>

app/views/categories/index.html.erb
<h2>Restaurant Categories</h2>
<%= link_to "Add a new Category", new_category_path %>

<% @categories.each do |cat| %>
  <p><%= link_to cat.category, category_path(cat) %></p>
<% end %>

app/views/categories/new.html.erb
<p>Add New Category</p>

<%= render "form" %>

app/views/categories/show.html.erb
<h2><%= @category.category %></h2>
<p>
  <%= link_to '(Delete Category)', category_path,
    method: :delete,
    data: { confirm: 'Are you sure?' } %>
</p>

<div class="categories_show">
<!-- this local variable `cat` is confusing since you're iterating over
restaurants. I believe 'restaurant' would be a better variable name here. -->
<% @category.restaurants.each do |cat| %>
  <h3><%= cat.name %></h3>
  <p><%= cat.address %></p>
  <p><%= image_tag (cat.photo_url) %></p>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RESREV</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1 id="title">RESREV</h1>


<nav>
  <%= link_to "HOME", root_path %>
  <%= link_to "ALL RESTAURANTS", restaurants_path %>
  <%= link_to "ADD NEW RESTAURANT", new_restaurant_path %>
  <%= link_to "CATEGORIES", categories_path %>
  <span class= "authentication">

    <% if current_user %>
       <%= link_to current_user.username, user_path(current_user) %>
      <%= link_to "SIGN OUT", signout_path %>
    <% else %>
      <%= link_to "SIGN IN", signin_path %>
      <%= link_to "SIGN UP", signup_path %>
    <% end %>
  </span>
</nav>

<% flash.each do |type, message| %>
  <p class= "flash <%= type %>">
    <%= message %>
  </p>
<% end %>

<div class="input">
<%= yield %>
</div>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <% if @restaurant.errors.any? %>
  <div id="error_explanation">
    <ul>
      <h2>errors:</h2>
      <% @restaurant.errors.full_messages.each do |message| %>
      <p><%= message %></p>
      <% end %>
    </ul>
  </div>
  <% end  %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>

  <p>
    <%= f.label :photo_url %><br>
    <%= f.text_field :photo_url %>
  </p>

  <p>
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :category %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/restaurants/edit.html.erb
<p>Edit Restaurant</p>

<%= render "form" %>

app/views/restaurants/index.html.erb
<h2>All Restaurants</h2>

<% @restaurants.each do |restaurant| %>
  <div class="container">

  <!--  looks like you're not using these wcontainer / icontainer classes... suggest
  removing them. (also, if you were to use them, I'd suggest changing them to be more descriptive)-->
    <div class="wcontainer">
      <h3><%= restaurant.name %></h3>
      <p><%= restaurant.address %></p>
      <p><%= link_to "Show", restaurant_path(restaurant) %></p>
    </div>
    <div class="icontainer">
    <p><%= image_tag(restaurant.photo_url) %></p>
    </div>
  </div>
<% end %>

app/views/restaurants/new.html.erb
<p>Add New Restaurant</p>

<%= render "form" %>

app/views/restaurants/show.html.erb
<h2 class="show_name">
  <%= @restaurant.name.upcase %>
  <%= link_to "(edit)", edit_restaurant_path %>
  <%= link_to '(delete)', restaurant_path,
                 method: :delete,
                 data: { confirm: 'Are you sure?' } %>
</h2>
<p><%= @restaurant.address %></p>
<p><%= image_tag (@restaurant.photo_url) %></p>

<h3 class="ratings_title"> Average Rating: <%= @restaurant.average_rating %> </h3>

<!-- don't forget to indent inside a form_for do ... end block. -->
<%= form_for [@restaurant,@rating] do |f| %>
<%= f.select(:value, 1..10) %>
<!--  you have redundant info because you used nested routes for the ratings inside restaurants
(note the form_for above has two attributes), but also you're passing in restaurant_id here as well
best practice would be to do one or the other.
-->
<%= f.hidden_field :restaurant_id, value: @restaurant.id %>
<%= f.submit "Rate this Restaurant" %>
<% end %>
<!--
Would also be nice if you showed a count of how many 1s, 2s, 3s, etc
a restaurant has gotten in terms of ratings.
-->


<h3 class="reviews_title"> REVIEWS:</h3>
<div class="review_box">
<% @restaurant.reviews.each do |rvw| %>
  <div class="review">
    <%= rvw.comment %>
    <%= link_to '(Delete)', review_path(rvw),
                   method: :delete,
                   data: { confirm: 'Are you sure?' } %>
    <%= link_to '(Edit)', edit_review_path(rvw) %>
  </div>
<% end %>
</div>

<!--  why not use the review partial here? -->
<%= form_for Review.new do |f| %>
  <%= f.text_area :comment %>
  <%= f.hidden_field :restaurant_id, value: @restaurant.id %>
  <%= f.submit %>
<% end %>

app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <ul>
        <h2>errors:</h2>
        <% @review.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <% end %>
      </ul>
    </div>
  <% end  %>

  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </p>

  <p>
    <%= f.submit %>
  </p>
 <% end %>

app/views/reviews/edit.html.erb
<h2>Edit Comment</h2>

<%= render "form" %>

app/views/users/new.html.erb
<h2>SIGN UP HERE</h2>

<%= form_for @user do |f| %>

<% if @user.errors.any? %>
  <div id="error-messages">
    <% @user.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>
<% end %>

<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>

<%= f.submit %>

<% end %>

app/views/users/show.html.erb
<p>USERNAME: <%= @user.username %></p>
<p>EMAIL ADDRESS: <%= @user.email %></p>
<p>AGE: Unknown</p>
<p>DOB: Unknown</p>
<p>HOBBIES: Unknown</p>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <style> img {display: block; margin-left: auto; margin-right: auto; margin-top: 150px} </style>
</head>
<body>
  <div class="bigpic">
    <%= image_tag("rrlogo.png") %>
  </div>

</body>
</html>